module.exports.msg = {
    userExist: "User Already Exists",
    userRegistered: "Register Successfully",
    invalidUser: "Invalid Credentials",
    userLogedIn : "Login Successfully",
    userLogout: "Logout Successfully",
    unAuthorized : "Unautherized Access",
    success : "Success",
    updateUser: "Update Successfully",
    noToken: "No Token Provided",
    userDeleted: "User Deleted Successfully",
    categoryExist: "Category Already Exists",
    created : "Created Successfully",
    dataNotFound: "Data Not Found",
    dataUpdated: "Data Updated Successfully",
    fieldNotExist: "No Data Provided",
    delete: "Deleted Successfully",
    subcategoryExist: "SubCategory Already Exists",
    productExist : "Product Already Exists",
    productimage: "productimage is required",
    subcategoryNotFound : "Subcategory Not Found",
    categoryNotFound: "Category Not Found",
    productNotFound: "Product Not Found",
    notAvailable: "Currently this section is not available",
    dataInserted: "Data Inserted Successfully",
    invalidFile: "Invalid csv file",
}

module.exports.statusCode = {
    dataNotFound: 404,
    success: 200,
    badRequest: 400,
    unauthorized: 401,
    internalError: 500,
    conflict: 409,
    forbidden: 403,
}